name: Publish Python Package

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-alpha"
      - "v*.*.*-alpha.*"
      - "v*.*.*-beta"
      - "v*.*.*-beta.*"
      - "v*.*.*-release"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Set version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        poetry version $VERSION
    - name: Configure Poetry
      run: |
        echo "Configuring Poetry for ${{ github.repository }}"
        poetry config repositories.github https://api.github.com/repos/${{ github.repository }}/packages/pypi
        poetry config http-basic.github ${{ github.actor }} ${{ secrets.GITHUB_TOKEN }}
    - name: Build and publish
      run: |
        poetry build
        echo "Publishing to GitHub Packages..."
        poetry publish -r github -vvv
    - name: Debug Information
      if: always()
      run: |
        echo "GitHub Actor: ${{ github.actor }}"
        echo "GitHub Repository: ${{ github.repository }}"
        echo "Poetry version:"
        poetry --version
        echo "Poetry configuration:"
        poetry config --list
        echo "Current directory contents:"
        ls -la
        echo "Dist directory contents:"
        ls -la dist/